language: php
cache:
  directories:
    - $HOME/.composer/cache    
php:
  - '7.2'
  - '7.3'
install:
  - composer install  
script:
  - ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1
  - ./vendor/bin/phpunit
